### ISSUE TITLE
NPM version outdated?

### ISSUE THREAD

**Issue by SBD580** [sitefinitysteve/nativescript-google-analytics#22]
Hi,

Is it possible that the version found in NPM although at 0.3.2 still include a specific version of google-services? 

Shay

**Comment by sitefinitysteve** [comment]
It's all listed here
https://github.com/sitefinitysteve/nativescript-google-analytics/blob/master/plugin/platforms/android/include.gradle

**Comment by SBD580** [comment]
Hi @sitefinitysteve thanks for the super quick response.
I can see at the source code that the version is the latest (aka '+') but when using npm to download the plugin as a dependency, looking at the file got downloaded under node_modules I see a specific version of google-services (9.2.0)

**Comment by SBD580** [comment]
Maybe it has to do with the wrapping of 

```
// [START gms_compile]
// [END gms_compile]
```
which I'm not familiar with. Is that some kind of a placeholder or something?

**Comment by sitefinitysteve** [comment]
Hmmm, let me check on this

On Dec 29, 2016 5:19 PM, "SBD580" <notifications@github.com> wrote:

Hi @sitefinitysteve <https://github.com/sitefinitysteve> thanks for the
super quick response.
I can see at the source code that the version is the latest (aka '+') but
when using npm to download the plugin as a dependency, looking at the file
got downloaded under node_modules I see a specific version of
google-services (9.2.0)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sitefinitysteve/nativescript-google-analytics/issues/22#issuecomment-269702439>,
or mute the thread

**Comment by elliottohara** [comment]
The NPM version still has google-services(9.2.0)

**Comment by sitefinitysteve** [comment]
Yeah sorry I'm away with no laptop to check it out

On Jan 3, 2017 10:19 PM, "elliottohara" <notifications@github.com> wrote:

The NPM version still has google-services(9.2.0)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/sitefinitysteve/nativescript-google-analytics/issues/22#issuecomment-270286364>,
or mute the thread

**Comment by ignaciolarranaga** [comment]
Another one here seeing the same problem, in the source it says:

```
dependencies {
    // [START gms_compile]
    compile 'com.google.android.gms:play-services-analytics:+'
    // [END gms_compile]
}
```

But when you download the module from npm it says:
```
dependencies {
    // [START gms_compile]
    compile 'com.google.android.gms:play-services-analytics:9.2.0'
    // [END gms_compile]
}
```

**Comment by sitefinitysteve** [comment]
I bumped the version to 3.3 and republished, can you try now?

**Comment by ignaciolarranaga** [comment]
Fixed. Thanks!

**Comment by SBD580** [comment]
Thanks!
